### ISSUE TITLE
Can't see how to re-arrange

### ISSUE THREAD

**Issue by gostega** [declanwoods/ManagedBookmarks#1]
Hi Declan, I've downloaded v1.3 of the tool, but can't see how to re-arrange bookmarks, any tips?
![image](https://user-images.githubusercontent.com/16591081/67651551-89858280-f97c-11e9-8ccd-9d31c4fdfc56.png)

**Comment by declanwoods** [comment]
Hey James,
You should just have to select the bookmark/folder you want to move, hold down the control key and use the up/down arrow keys to move the item
